version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: valuta-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
    restart: always
    networks:
      - valuta-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: valuta-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - valuta-net
    environment:
      - API_URL=http://backend:8000
      - PYTHONUNBUFFERED=1
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

networks:
  valuta-net:
    driver: bridge